name: DRO Heaalth Pharmacy
description: DRO's Heaalth Pharmacy
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.8.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  #Flutter Dependencies here
  progress_dialog: ^1.2.1
  provider: ^3.2.0
  hexcolor: ^1.0.2
  lottie: ^0.4.1
  flutter_dotenv: ^2.1.0
  shared_preferences: ^0.5.8
  mdi: ^3.0.0
  fluttertoast: ^4.0.1
  flutter_launcher_icons: "^0.7.3"
  flutter_fadein: ^1.1.1
  simple_animations: ^1.3.4
  page_transition: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


dependency_overrides:
  intl: ^0.16.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
  fonts:

    - family: CircularStd
      fonts:
        - asset: aassets/fonts/circular-std/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/circular-std/CircularStd-Medium.ttf
          weight: 300
        - asset: assets/fonts/circular-std/CircularStd-Book.ttf
          weight: 200

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true